/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swingcrud;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.GroupLayout.ParallelGroup;
import javax.swing.GroupLayout.SequentialGroup;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.JTextComponent;

import br.com.ceub.bo.Pessoa;
import br.com.ceub.fachada.FachadaPessoa;

/**
 *
 * @author JAMES
 */
public class Crud extends javax.swing.JFrame {

	/**
	 * Creates new form Crud
	 */
	Connection con;
	Statement st;
	ArrayList<User> students = new ArrayList<>();
	private FachadaPessoa fachadaPessoa;
	private JTextField txtId;
	private JLabel jLabel5;
	private String idLinhaSelecionada;

	public String getIdLinhaSelecionada() {
		return idLinhaSelecionada;
	}

	public void setIdLinhaSelecionada(String idLinhaSelecionada) {
		this.idLinhaSelecionada = idLinhaSelecionada;
	}

	public Crud() {
		initComponents();
		fetch();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		txtNome = new javax.swing.JTextField();
		// txtId = new javax.swing.JTextField();
		jLabelNome = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		txtEndereco = new javax.swing.JTextField();
		txtTelefone = new javax.swing.JTextField();
		txtId = new javax.swing.JTextField();
		txtId.setEditable(false);
		jLabel3 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tblStudents = new javax.swing.JTable();
		btnSave = new javax.swing.JButton();
		btnUpdate = new javax.swing.JButton();
		btnDelete1 = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Cadadtro Rogerio");
		setResizable(false);

		jLabelNome.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
		jLabelNome.setText("Nome");

		jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
		jLabel2.setText("Telefone");

		jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
		jLabel3.setText("Enredeço");
		jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
		jLabel5.setText("Id");

		tblStudents.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Nome", "Telefone", "Endereco", "Id" }) {
			boolean[] canEdit = new boolean[] { false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		tblStudents.setCellSelectionEnabled(true);
		tblStudents.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				tblClienteMouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(tblStudents);
		if (tblStudents.getColumnModel().getColumnCount() > 0) {
			tblStudents.getColumnModel().getColumn(2).setResizable(false);
		}

		btnSave.setText("Salvar");
		btnSave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
		btnSave.setIconTextGap(0);
		btnSave.setInheritsPopupMenu(true);
		btnSave.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSaveActionPerformed(evt);
			}
		});

		btnUpdate.setText("Atualizar");
		btnUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
		btnUpdate.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnUpdateActionPerformed(evt);
			}
		});

		btnDelete1.setText("Remover");
		btnDelete1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
		btnDelete1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDelete1ActionPerformed(evt);
			}
		});

		jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jLabel4.setText("Crud Rogerio");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);

		SequentialGroup componentLabelId = layout.createSequentialGroup()
				.addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 74,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(8, 8, 8).addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 133,
						javax.swing.GroupLayout.PREFERRED_SIZE);

		SequentialGroup componentLabelNome = layout.createSequentialGroup()
				.addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 74,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(18, 18, 18).addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 163,
						javax.swing.GroupLayout.PREFERRED_SIZE);
		ParallelGroup addGroup = layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(componentLabelNome).addGroup(componentLabelId)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 163,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 163,
										javax.swing.GroupLayout.PREFERRED_SIZE)));
		SequentialGroup addPreferredGap = layout.createSequentialGroup().addGroup(addGroup)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE);
		ParallelGroup addGroup2 = layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(addPreferredGap)
								.addGroup(layout.createSequentialGroup()
										.addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 72,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 75,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(27, 27, 27).addComponent(btnDelete1,
												javax.swing.GroupLayout.PREFERRED_SIZE, 75,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap())
				.addGroup(layout.createSequentialGroup().addGap(218, 218, 218).addComponent(jLabel4)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setHorizontalGroup(addGroup2);
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(30, 30, 30)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(30, 30, 30)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(39, 39, 39)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(btnDelete1,
																javax.swing.GroupLayout.PREFERRED_SIZE, 39,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE,
																39, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 234,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(29, Short.MAX_VALUE)));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	public Pessoa criaPessoa() {
		Pessoa pessoa = new Pessoa();
		String nome = txtNome.getText().trim();
		String endereco = txtEndereco.getText().trim();
		String telefone = txtTelefone.getText().trim();
//		String id = txtId.getText().trim();
		pessoa.setNome(nome);
		pessoa.setEndereco(endereco);
		pessoa.setTelefone(telefone);
		try {			
			pessoa.setId(new Integer(idLinhaSelecionada));
		} catch (Exception e) {
			// TODO: handle exception
		}
		return pessoa;
	}

	private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSaveActionPerformed
		try {
			Pessoa p = criaPessoa();
			salvarPessoa();
			DefaultTableModel model = (DefaultTableModel) tblStudents.getModel();
			Object[] row = new Object[4];
			row[0] = p.getNome();
			row[1] = p.getEndereco();
			row[2] = p.getTelefone();
			model.addRow(row);
			clear();
		} catch (Exception ex) {
			Logger.getLogger(Crud.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUpdateActionPerformed
		// TODO add your handling code here:
		String nome = txtNome.getText().trim();
		String telefone = txtEndereco.getText().trim();
		String endereco = txtTelefone.getText().trim();
		if (!nome.isEmpty() && !telefone.isEmpty() && !endereco.isEmpty()) {
			try {

				alterarPessoa();
				DefaultTableModel model = (DefaultTableModel) tblStudents.getModel();
				model.setRowCount(0);
				fetch();
				alert("Alterado, Rogério!");

			} catch (Exception ex) {
				Logger.getLogger(Crud.class.getName()).log(Level.SEVERE, null, ex);
			}
		} else {
			alert("Vai Atualizar Oq?", "Seleciona a linha la, Porra!");
		}
	}// GEN-LAST:event_btnUpdateActionPerformed

	// set the values of a row to the textfields
	private void tblClienteMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tblStudentsMouseClicked
		// TODO add your handling code here:
		int i = tblStudents.getSelectedRow();
		TableModel model = tblStudents.getModel();
		txtNome.setText(model.getValueAt(i, 0).toString());
		txtEndereco.setText(model.getValueAt(i, 1).toString());
		txtTelefone.setText(model.getValueAt(i, 2).toString());
		setIdLinhaSelecionada((model.getValueAt(i, 3).toString()));
	}// GEN-LAST:event_tblStudentsMouseClicked

	// handles delete button action
	private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDelete1ActionPerformed
		// TODO add your handling code here:
		int i = tblStudents.getSelectedRow();
		if (i >= 0) {
			int option = JOptionPane.showConfirmDialog(rootPane, "Vai remover mermo?", "Confirmação de Remoção",
					JOptionPane.YES_NO_OPTION);
			if (option == 0) {
				TableModel model = tblStudents.getModel();
				delete(getIdLinhaSelecionada());
				String id = model.getValueAt(i, 2).toString();
				if (tblStudents.getSelectedRows().length == 1) {
					delete(id);
					DefaultTableModel model1 = (DefaultTableModel) tblStudents.getModel();
					model1.setRowCount(0);
					fetch();
					clear();
				}
			}
		} else {
			alert("tem q selecionar a linha");
		}
	}// GEN-LAST:event_btnDelete1ActionPerformed

	// method to show an info alert
	public void alert(String msg) {
		JOptionPane.showMessageDialog(rootPane, msg);
	}

	// method to show an error alert
	public void alert(String msg, String title) {
		JOptionPane.showMessageDialog(rootPane, msg, title, JOptionPane.ERROR_MESSAGE);
	}

	// method to save user to the db
	public void salvarPessoa() {
		try {
			Pessoa pessoa = criaPessoa();
			getFachadaPessoa().insere(pessoa);
		} catch (Exception ex) {
			Logger.getLogger(Crud.class.getName()).log(Level.SEVERE, null, ex);
		}
		// fetch();
	}

	protected FachadaPessoa getFachadaPessoa() {
		if (this.fachadaPessoa == null) {
			this.fachadaPessoa = new FachadaPessoa();
		}
		return this.fachadaPessoa;
	}

	// update the db
	public void alterarPessoa() {
		Pessoa criaPessoa = criaPessoa();
		try {
			getFachadaPessoa().atualiza(criaPessoa);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		// fetch();
	}

	public void delete(String id) {
		try {
			getFachadaPessoa().remove(new Integer(id));
		} catch (NumberFormatException | SQLException e) {
			e.printStackTrace();
		}
		fetch();
	}

	// method to clear the txt fields
	private void clear() {
		txtNome.setText("");
		txtEndereco.setText("");
		txtTelefone.setText("");
		txtId.setText("");
	}

	// fetch
	private void fetch() {
		students.clear();
		try {
			List<Pessoa> pessoas = getFachadaPessoa().consultaPorNome(null);
			DefaultTableModel model = (DefaultTableModel) tblStudents.getModel();
			for (Pessoa p : pessoas) {

				Object[] row = new Object[4];
				row[0] = p.getNome();
				row[1] = p.getTelefone();
				row[2] = p.getEndereco();
				row[3] = p.getId();

				model.addRow(row);
			}

		} catch (Exception ex) {
			Logger.getLogger(Crud.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> {
			new Crud().setVisible(true);
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnDelete1;
	private javax.swing.JButton btnSave;
	private javax.swing.JButton btnUpdate;
	private javax.swing.JLabel jLabelNome;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tblStudents;
	private javax.swing.JTextField txtNome;
	private javax.swing.JTextField txtTelefone;
	private javax.swing.JTextField txtEndereco;
	// End of variables declaration//GEN-END:variables
}
